// Generated by ReScript, PLEASE EDIT WITH CARE

import * as App from "./App.bs.js";
import * as React from "react";
import * as Js_exn from "rescript/lib/es6/js_exn.js";
import * as ReactDom from "react-dom";
import * as Caml_option from "rescript/lib/es6/caml_option.js";

import './index.css'
;

var root = document.querySelector("#root");

if (root == null) {
  Js_exn.raiseError("Root not found!");
} else {
  ReactDom.render(React.createElement(React.StrictMode, {
            children: React.createElement(App.make, {})
          }), root);
}

var root$1 = (root == null) ? undefined : Caml_option.some(root);

export {
  root$1 as root,
  
}
/*  Not a pure module */
